CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) UNIQUE NOT NULL);

CREATE TABLE tasks (
  id SERIAL PRIMARY KEY,
  title VARCHAR(150) UNIQUE NOT NULL,
  description TEXT NOT NULL,
  due_date DATE,
  status VARCHAR(20) DEFAULT 'Pending',
  FOREIGN KEY (user_id) REFERENCES users(id));
